version: "3"

services:
 tekskil_server_case_ui:
  #image: tekskil_server_case_ui
  build:
   context: ./tcs_ui
   dockerfile: Dockerfile
  network_mode: "host"
  privileged: true
  volumes:
   - ./tcs_ui/case_ui:/app #used for development only to keep python code live
   - /home/tch/apps/tcs_ui/tcs_ui_pipe:/app/compipe
  restart: on-failure
  
 tekskil_discovery_broadcast:
  build:
   context: ./TS_DISCOVERY_BROADCAST
   dockerfile: Dockerfile
  network_mode: "host"
  volumes:
   - /home/tch/apps/tcs_ui/version:/app/tcs_version
  restart: on-failure



