version: "3"

services:
 tekskil_server_case_ui:
  #image: tekskil_server_case_ui
  build:
   context: ./tcs_ui
   dockerfile: Dockerfile
  network_mode: "host"
  privileged: true
  volumes:
   - ./tcs_ui/case_ui:/app #keep python code live to updates
   - /home/tch/apps/tcs_ui/tcs_ui_pipe:/app/compipe
   - /home/tch/apps/tcs_ui/version:/app/tcs_version
   - /home/tch/apps/docker/tkskl-server/.env:/app/tkskl-server/version.txt
  restart: on-failure
  
 tekskil_discovery_broadcast:
  build:
   context: ./TS_DISCOVERY_BROADCAST
   dockerfile: Dockerfile
  network_mode: "host"
  volumes:
   - /home/tch/apps/tcs_ui/version:/app/tcs_version
   - /home/tch/apps/docker/tkskl-server/.env:/app/tkskl-server/version.txt
  restart: on-failure



